name: CI WAS Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tenablescan:
    name: was-cicd
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repo
        uses: actions/checkout@v2

      # 2️⃣ Levantar la aplicación PetStore
      - name: Build and Run PetStore
        run: |
          docker pull swaggerapi/petstore
          docker run -d --name petstore -p 8080:8080 swaggerapi/petstore

      # 3️⃣ Ejecutar el escaneo Tenable WAS
      - name: Run Tenable WAS Scan
        run: |
          # Crear directorio para resultados con timestamp
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          REPORT_DIR="scanner_results_$TIMESTAMP"
          mkdir -p "$REPORT_DIR"

          docker pull tenable/was-scanner:latest

          # Ejecutar contenedor de Tenable WAS
          docker run \
            -v "$(pwd):/scanner" \
            -t \
            -e WAS_MODE=cicd \
            -e ACCESS_KEY="${ACCESS_KEY}" \
            -e SECRET_KEY="${SECRET_KEY}" \
            -e CONFIG_FILE=/scanner/tenable_was.conf \
            -e WAS_URL=http://petstore:8080 \
            -e REPORT_DIR=/scanner/$REPORT_DIR \
            --link petstore \
            tenable/was-scanner:latest || true

          echo "=== Archivos generados ==="
          ls -la "$REPORT_DIR"
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      # 4️⃣ Subir resultados como artifact
      - name: Upload Tenable WAS report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tenable-was-report
          path: scanner_results_*/
